version: '3.5'

services:
    redis:
        image: 'redis:3.0-alpine'
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/var/lib/redis/data'
        ports:
            - '6379:6379'

    website:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            "fantasyapp.app:create_app()"
        environment:
            PYTHONUNBUFFERED: 'true'
        volumes:
            - '.:/fantasyapp'
        ports:
            - '8000:8000'

    celery:
        build: .
        command: celery worker -l info -A fantasyapp.blueprints.contact.tasks
        env_file:
            - '.env'
        volumes:
            - '.:/fantasyapp'

volumes:
    redis:
