version: '3.5'

services:
    postgres:
        image: 'postgres:10.0'
        env_file:
            - '.env'
        volumes:
            - 'postgres:/var/lib/postgresql/data'

    redis:
        image: 'redis:3.2.11-alpine'
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/var/lib/redis/data'

    website:
        build: .
        command: >
            gunicorn -c "python:config.gunicorn"
            --reload
            "fantasyapp.app:create_app()"
        env_file:
            - '.env'
        volumes:
            - '.:/fantasyapp'
        expose:
            - "8000"
        depends_on:
            - postgres
            - redis

    celery:
        build: .
        command: celery worker -l info -A fantasyapp.blueprints.contact.tasks
        env_file:
            - '.env'
        volumes:
            - '.:/fantasyapp'
        depends_on:
            - postgres
            - redis

    nginx:
        restart: always
        build: ../deploy/nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - website

volumes:
    postgres:
    redis:
