version: '3.5'

services:
    postgres:
        image: 'postgres:10.0'
        env_file:
            - '.env'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        ports:
            - '5432:5432'

    redis:
        image: 'redis:3.2.11-alpine'
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/var/lib/redis/data'
        ports:
            - '6379:6379'

    website:
        build: .
        command: >
            gunicorn -c "python:config.gunicorn"
            --reload
            "fantasyapp.app:create_app()"
        env_file:
            - '.env'
        volumes:
            - '.:/fantasyapp'
        ports:
            - '8000:8000'

    celery:
        build: .
        command: celery worker -l info -A fantasyapp.blueprints.contact.tasks
        env_file:
            - '.env'
        volumes:
            - '.:/fantasyapp'

volumes:
    postgres:
    redis:
